### ISSUE TITLE
BE 코드에서 린트 에러가 발생하는 문제

### ISSUE THREAD

**Issue by parkblo** [boostcampwm-2024/web29-honeyflow#130]
## 🔍 이슈 설명
![image](https://github.com/user-attachments/assets/5e64fe29-03f1-4f3d-9a2c-4cfdc8c1e724)
BE 코드에서 린트 에러가 다수 발생하여 해결이 필요해보입니다.

## ✅ 인수 조건
- 작성된 코드들에서 린트 에러가 검출되지 않는다.

## 🚜 작업 사항
- [ ] 린트 설정 수정

**Comment by fru1tworld** [comment]
.eslintignore 설정으로 해결
