### ISSUE TITLE
Lint 상 모듈 임포트 시 ts, tsx 파일에 대해 확장자를 모두 요구하는 문제

### ISSUE THREAD

**Issue by hoqn** [boostcampwm-2024/web29-honeyflow#79]
## 🔍 이슈 설명

<img width="499" alt="스크린샷 2024-11-07 오후 1 13 40" src="https://github.com/user-attachments/assets/382d944b-cac7-42d1-905f-4639fc39d731">

airbnb lint 규칙 상, `ts`, `tsx` 파일을 import할 때 확장자를 반드시 기입해야 하는 규칙이 적용되어 있었어요. 이는 다음([airbnb lint의 기본 설정](https://github.com/airbnb/javascript/blob/6499695ac11c4640ed0f77f8865a1adcb32d3239/packages/eslint-config-airbnb-base/rules/imports.js#L138)이에요)과 같이 airbnb lint가 기본적으로 js 환경에만 대응되어 있기 때문이라 생각해요.

<img width="401" alt="스크린샷 2024-11-07 오후 1 05 05" src="https://github.com/user-attachments/assets/96d741a1-b04b-42b5-9323-d74f8f19c5eb">

이에, 이 룰을 확장하여 `ts`와 `tsx`까지 적용해 확장자를 생략할 수 있도록 하고자 해요.

**다만, 이 룰을 전체적으로 수정할지(root), 아니면 하위 패키지(`frontend`, `backend`)에서만 각각 수정할지에 대해 의견이 궁금해요.**

## ✅ 인수 조건

- `ts`, `tsx` 파일에 대해 확장자를 생략해도 lint 오류가 발생하지 않아요.
- `ts`, `tsx` 파일에 대해 확장자를 넣는다면 lint 오류가 발생해요.

## 🚜 작업 사항
- [ ] 

## 📌 참고 자료

- https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb-base/rules/imports.js#L138

**Comment by parkblo** [comment]
프론트엔드에서는 vite가 확장자를 자동으로 찾아주는 것으로 알고있어서 규칙을 제거해도 좋을 것 같습니다.
백엔드는 확장자가 있도록 강제하는 것이 에러를 막을 수 있어서 유리할 것 같다고 생각하는데, 다른 분들 의견도 궁금합니다!
